# https://github.com/Homebrew/homebrew-bundle

tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "olets/tap"
tap "stripe/stripe-cli"
tap "teamookla/speedtest"

# Homebrew
# https://github.com/Homebrew/brew/

brew "advancecomp"
brew "ansible"
brew "asciidoctor"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "diff-so-fancy"
brew "docutils"
brew "dos2unix"
brew "exa"
brew "fd"
brew "fish"
brew "fontforge"
brew "fonttools"
brew "fzf"
brew "gh"
brew "gifsicle"
brew "git"
brew "git-quick-stats"
brew "gmp"
brew "highlight"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jhead"
brew "jq"
brew "lazygit"
brew "less"
brew "libtermkey"
brew "mas"
brew "media-info"
brew "memcached"
brew "most"
brew "neofetch"
brew "neovim"
brew "node"
brew "olets/tap/zsh-abbr"
brew "onefetch"
brew "openssl"
brew "overmind"
brew "pandoc"
brew "perl"
brew "pgcli"
brew "postgresql@14", restart_service: :changed
brew "pstree"
brew "ranger"
brew "readline"
brew "redis", restart_service: :changed
brew "ripgrep"
brew "rlwrap"
brew "rsync"
brew "rust"
brew "shellcheck"
brew "sqlite"
brew "ssh-copy-id"
brew "starship"
brew "stow"
brew "stripe/stripe-cli/stripe"
brew "teamookla/speedtest/speedtest"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "universal-ctags"
brew "w3m"
brew "wget"
brew "xz"
brew "yamllint"
brew "yarn"
brew "zsh"

brew "libyaml" # should be installed after openssl

# homebrew-cask
# https://github.com/Homebrew/homebrew-cask
#
# Critical Programs
# These are programs I usually need to install immediately on a new machine.
# For this reason, they don't do so well being managed by Homebrew.
# cask "1password"
# cask "google-chrome"
# cask "dropbox"

cask "1password-cli"
cask "alfred"
cask "arq"
cask "bartender"
cask "brave-browser"
cask "carbon-copy-cloner"
cask "cleanmymac"
cask "daisydisk"
cask "expressvpn"
cask "firefox"
cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-victor-mono-nerd-font"
cask "freedom"
cask "google-drive"
cask "grammarly-desktop"
cask "hazel"
cask "istat-menus"
cask "iterm2-beta"
cask "loom"
cask "messenger"
cask "microsoft-edge"
cask "microsoft-excel"
cask "microsoft-word"
cask "ngrok"
cask "notion"
cask "obsidian"
cask "postico"
cask "screenflick"
cask "signal"
cask "slack"
cask "tableplus"
cask "telegram"
cask "todoist"
cask "viber"
cask "whatsapp"
cask "zoom"

# rubocop:disable Style/NumericLiterals
mas "1Password for Safari", id: 1569813296
mas "e-Sword X", id: 968437868
mas "Keynote", id: 409183694
mas "Logic Pro", id: 634148309
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Toggl Track", id: 1291898086
# rubocop:enable Style/NumericLiterals

# vim: set filetype=ruby:
