# https://github.com/Homebrew/homebrew-bundle

tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
# tap "puma/puma"
tap "stripe/stripe-cli"
tap "teamookla/speedtest"

# Homebrew
# https://github.com/Homebrew/brew/

brew "advancecomp"
brew "asciidoctor"
brew "asdf"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bat"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "diff-so-fancy"
brew "dos2unix"
brew "exa"
brew "fd"
brew "fish"
brew "fontforge"
brew "fonttools"
brew "fzf"
brew "gh"
brew "gifsicle"
brew "git"
brew "git-quick-stats"
brew "gmp" # Vim dependency
brew "highlight"
brew "htop"
brew "httpie"
brew "imagemagick"
brew "jhead"
brew "jq"
brew "lazygit"
brew "less"
brew "libtermkey"
brew "mas"
brew "media-info"
brew "memcached"
brew "most"
brew "neofetch"
brew "neovim"
brew "onefetch"
brew "openssl"
brew "openssl@1.1" # wget dependency
brew "overmind"
brew "pandoc"
brew "perl"
brew "pgcli"
brew "postgresql@14", restart_service: :changed
brew "pstree"
brew "python3"
brew "ranger"
brew "readline"
brew "redis"
brew "ripgrep"
brew "rlwrap"
brew "rsync"
brew "rust"
brew "shellcheck"
brew "speedtest"
brew "sqlite"
brew "ssh-copy-id"
brew "starship"
brew "stripe/stripe-cli/stripe"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "w3m"
brew "wget"
brew "xz"
brew "yamllint"
brew "zsh"

# homebrew-cask
# https://github.com/Homebrew/homebrew-cask
cask "1password"
cask "1password-cli"
cask "alfred"
cask "arq"
cask "brave-browser"
cask "carbon-copy-cloner"
cask "cleanmymac"
cask "daisydisk"
cask "dropbox"
cask "expressvpn"
cask "firefox"
cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-iosevka-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-victor-mono-nerd-font"
cask "freedom"
cask "google-chrome"
cask "google-drive"
cask "grammarly-desktop"
cask "hazel"
cask "istat-menus"
cask "iterm2-beta"
cask "messenger"
cask "microsoft-edge"
cask "microsoft-excel"
cask "microsoft-word"
cask "ngrok"
cask "notion"
cask "postico"
cask "signal"
cask "slack"
cask "tableplus"
cask "telegram"
cask "toggl-track"
cask "viber"
cask "vmware-fusion"
cask "whatsapp"
cask "zoom"

# rubocop:disable Style/NumericLiterals
mas "1Password for Safari", id: 1569813296
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "Numbers", id: 409203825
mas "OmniGraffle", id: 1142578753
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Things 3", id: 904280696
mas "e-Sword", id: 968437868
# rubocop:enable Style/NumericLiterals

# vim: set filetype=ruby:
