### GET request example ###

# host
https://reqres.in

# curl options
--connect-timeout 10

# query
GET /api/users/2

### POST request example ###

# host
https://reqres.in

# query
POST /api/users
{
    "name": "morpheus",
    "job": "leader"
}

# https://github.com/diepm/vim-rest-console#5-usage
