#!/usr/bin/env bash
#
# Generate Zsh abbreviations from shared YAML source
# Usage: ./generate-zsh-abbr.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
YAML_FILE="$SCRIPT_DIR/abbreviations.yaml"
OUTPUT_FILE="$SCRIPT_DIR/../zsh/.config/zsh-abbr/abbreviations.zsh"

if ! command -v yq >/dev/null 2>&1; then
    echo "Error: yq is required but not installed. Install it with: brew install yq"
    exit 1
fi

if [[ ! -f "$YAML_FILE" ]]; then
    echo "Error: YAML file not found: $YAML_FILE"
    exit 1
fi

echo "Generating Zsh abbreviations from $YAML_FILE..."

# Generate the header
cat > "$OUTPUT_FILE" << 'EOF'
# Zsh abbreviations - Generated from shared/abbreviations.yaml
# DO NOT EDIT THIS FILE DIRECTLY - Edit shared/abbreviations.yaml instead
# Regenerate with: bash shared/generate-zsh-abbr.sh
#
# https://zsh-abbr.olets.dev

EOF

# Process each category in the YAML file
yq eval '. as $root | keys | .[]' "$YAML_FILE" | while read -r category; do
    echo "# $(echo "$category" | tr '_' ' ' | awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1')" >> "$OUTPUT_FILE"
    
    yq eval ".${category} | to_entries | .[] | \"abbr \\\"\" + .key + \"\\\"=\\\"\" + .value + \"\\\"\"" "$YAML_FILE" >> "$OUTPUT_FILE"
    
    echo "" >> "$OUTPUT_FILE"
done

# Add note about functions that replace some abbreviations
cat >> "$OUTPUT_FILE" << 'EOF'

# Note: Some abbreviations have been replaced by smart functions:
# - gpum: Use gpum function (smart git push with upstream tracking)
# - grbm: Use grbm function (smart git rebase against default branch)
# - gcom: Use gcom function (smart git checkout default branch)
EOF

echo "✅ Generated Zsh abbreviations: $OUTPUT_FILE"
echo "📊 Total abbreviations: $(grep -c '^abbr' "$OUTPUT_FILE")"