" exe 'source' stdpath('config') . '/colorschemes/material.vim'
" exe 'source' stdpath('config') . '/colorschemes/nightfly.vim'
" exe 'source' stdpath('config') . '/colorschemes/night-owl.vim'
" exe 'source' stdpath('config') . '/colorschemes/one.vim'
exe 'source' stdpath('config') . '/colorschemes/solarized.vim'
