return {
  {
    "mason-org/mason.nvim",
    opts = {
      ensure_installed = {
        "bash-language-server",
        "css-lsp",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "eslint-lsp",
        "flake8",
        "hadolint",
        "herb-language-server",
        "html-lsp",
        "json-lsp",
        "lua-language-server",
        "markdown-toc",
        "markdownlint",
        "markdownlint-cli2",
        "marksman",
        "prettier",
        "shellcheck",
        "shfmt",
        "sqlfluff",
        "stylua",
        "tailwindcss-language-server",
        "taplo",
        "typescript-language-server",
        "vim-language-server",
        "vue-language-server",
        "yaml-language-server",
      },
    },
  },
}
